### PR TITLE
Vbe 1073

### PR DESCRIPTION
**Pull request by fp-anibal**
https://foodpanda.atlassian.net/browse/VBE-1073

### CODE REVIEW

**Comment by d-tylczynski-foodpanda** [comment]
`.gradle` files should be included?

**Comment by d-tylczynski-foodpanda** [comment]
and `.idea`?

**Comment by d-tylczynski-foodpanda** [comment]
@fp-anibal can you put also short description in the pull-request title and in the commit name, so it will appear in Git history?

**Comment by fp-anibal** [comment]
Yep, .idea and .gradle files are automatically updated when you use a new version of Gradle and a new Android SDK version to compile the project.

**Comment by fp-anibal** [comment]
Removed all the iml, idea and gradle files and renamed the commits.... with the help of Vicente!

**Comment by d-tylczynski-foodpanda** [comment]
I see that `.gradle/2.1/taskArtifacts/` and other are still in the commit, can we remove?

**Comment by d-tylczynski-foodpanda** [comment]
http://stackoverflow.com/questions/1274057/making-git-forget-about-a-file-that-was-tracked-but-is-now-in-gitignore

**Comment by d-tylczynski-foodpanda** [comment]
Besides that :+1:

**Comment by fp-anibal** [comment]
I don't see that .gradle/2.1/taskArtifacts/ anywhere... we removed all in the https://github.com/foodpanda/Android-BluetoothSPPLibrary/pull/1/commits/353b9c7005c3061ad3edea9c43acb3e155c3a43f commit

**Comment by d-tylczynski-foodpanda** [comment]
it's there on list of files of PR

**Comment by d-tylczynski-foodpanda** [comment]
Ah, it's removing so :+1:

**Comment by kotya341** [comment]
just curious
In my git ignore I have `app/manifest-merger-release-report.txt`maybe you can exclude this report as well

**Comment by d-tylczynski-foodpanda** [comment]
@fp-anibal can we resolve above comment to get :+1:  :)

**Comment by fp-anibal** [comment]
git ignore updated.

**Comment by kotya341** [comment]
👍  
I am not sure that you will releases this way however better to cover all cases

**Comment by d-tylczynski-foodpanda** [comment]
We have 2 :+1: @fp-anibal let's merge and then let's prepare https://github.com/foodpanda/vendor-backend-app-android/pull/8 for merging :)

**Comment by d-tylczynski-foodpanda** [comment]
:dancer: and delete the branch :)

**Pull request merged**
